app:
  name: Phalcon Blog
  author: "Phalcon Team"
  description: "We are an open source web framework for PHP delivered as a C extension offering high performance and lower resource consumption"
  keywords: "php, phalcon, phalcon php, php framework, faster php framework"
  generator: "Github Pages"
  avatar: https://avatars3.githubusercontent.com/u/1221505?v=4
  baseurl: "/"

social:
  email: team@phalconphp.com
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

meta:
  disqus:
  google_analytics: UA-90300500-3

excerpt_separator: <!--more-->

paginate: 5
paginate_path: "/page-:num"
permalink: /post/:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

sass:
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
