app:
  name: Phalcon Blog
  author: "Phalcon Team"
  description: "We are an open source web framework for PHP delivered as a C extension offering high performance and lower resource consumption"
  keywords: "php, phalcon, phalcon php, php framework, faster php framework"
  generator: "Github Pages"
  avatar: https://avatars3.githubusercontent.com/u/1221505?v=4
  baseurl: "/"

social:
  email: team@phalconphp.com
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

meta:
  disqus:
  google_analytics: 'UA-133802124-2'

excerpt_separator: <!--more-->

paginate: 5
paginate_path: "/page-:num"
permalink: /post/:title
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

algolia:
  application_id: 'QZSIJXM8NK'
  index_name: 'phalcon-blog'
  search_only_api_key: 'ed266d1fbb836f531f335570585c3c07'

sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
